/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabajofinallira;

/**
 *
 * @author emira
 */
public class AgendarCita extends javax.swing.JFrame {

    Tiket ticket = new Tiket();
    /**
     * Creates new form AgendarCita
     */
    public AgendarCita() {
        initComponents();
        setLocationRelativeTo(null);
        AlmecenarCliente.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        telefono = new javax.swing.JLabel();
        vehiculo = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        ser = new javax.swing.JLabel();
        Nombre_Tex = new javax.swing.JTextField();
        Numero_Telefono = new javax.swing.JTextField();
        Marco_Cliente = new javax.swing.JTextField();
        Hora_Cliente = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        btn_Regresar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_Editar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AlmecenarCliente = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Tipo_Servicios = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        jTextField5.setText("jTextField5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Barlow Black", 3, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josty25\\Documents\\NetBeansProjects\\EQUIPO7\\src\\com\\mycompany\\proyectofinal\\Imagenes\\Login.png")); // NOI18N
        Titulo.setText("  HOLA ¿AQUIEN VAMOS AGREGAR HOY?");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 530, -1));

        Nombre.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josty25\\Documents\\NetBeansProjects\\EQUIPO7\\src\\com\\mycompany\\proyectofinal\\Imagenes\\Simon2XD.png")); // NOI18N
        Nombre.setText("DIGITE EL NOMBRE DEL CLIENTE ");
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 260, 29));

        telefono.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        telefono.setForeground(new java.awt.Color(255, 255, 255));
        telefono.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josty25\\Documents\\NetBeansProjects\\EQUIPO7\\src\\com\\mycompany\\proyectofinal\\Imagenes\\Simon2XD.png")); // NOI18N
        telefono.setText("NUMERO DE TELEFONO DEL CLIENTE");
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 280, 28));

        vehiculo.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        vehiculo.setForeground(new java.awt.Color(255, 255, 255));
        vehiculo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josty25\\Documents\\NetBeansProjects\\EQUIPO7\\src\\com\\mycompany\\proyectofinal\\Imagenes\\Simon2XD.png")); // NOI18N
        vehiculo.setText("MARCA");
        jPanel1.add(vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 178, 31));

        hora.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        hora.setForeground(new java.awt.Color(255, 255, 255));
        hora.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josty25\\Documents\\NetBeansProjects\\EQUIPO7\\src\\com\\mycompany\\proyectofinal\\Imagenes\\Simon2XD.png")); // NOI18N
        hora.setText("PRECIO");
        jPanel1.add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 178, 27));

        ser.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ser.setForeground(new java.awt.Color(255, 255, 255));
        ser.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josty25\\Documents\\NetBeansProjects\\EQUIPO7\\src\\com\\mycompany\\proyectofinal\\Imagenes\\Simon2XD.png")); // NOI18N
        ser.setText("SERVICIO O PROMOCION: ");
        jPanel1.add(ser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 220, 27));

        Nombre_Tex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_TexActionPerformed(evt);
            }
        });
        jPanel1.add(Nombre_Tex, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 280, 29));

        Numero_Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero_TelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(Numero_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 280, 28));
        jPanel1.add(Marco_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 280, 31));

        Hora_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hora_ClienteActionPerformed(evt);
            }
        });
        jPanel1.add(Hora_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 280, 27));

        Guardar.setBackground(new java.awt.Color(0, 204, 204));
        Guardar.setFont(new java.awt.Font("Barlow Black", 3, 14)); // NOI18N
        Guardar.setForeground(new java.awt.Color(0, 0, 0));
        Guardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josty25\\Documents\\NetBeansProjects\\EQUIPO7\\src\\com\\mycompany\\proyectofinal\\Imagenes\\SaveXD.png")); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 124, -1));

        btn_Regresar.setBackground(new java.awt.Color(0, 204, 204));
        btn_Regresar.setFont(new java.awt.Font("Barlow Black", 3, 14)); // NOI18N
        btn_Regresar.setForeground(new java.awt.Color(0, 0, 0));
        btn_Regresar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josty25\\Documents\\NetBeansProjects\\EQUIPO7\\src\\com\\mycompany\\proyectofinal\\Imagenes\\Simon1XD.png")); // NOI18N
        btn_Regresar.setText("Regresar");
        btn_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 120, -1));

        btn_Editar.setText("Editar");
        btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarActionPerformed(evt);
            }
        });

        AlmecenarCliente.setColumns(20);
        AlmecenarCliente.setRows(5);
        jScrollPane1.setViewportView(AlmecenarCliente);

        jLabel7.setText("LISTA DE CLIENTES ");

        jButton1.setText("Guardar");

        jButton2.setText("IMPRIMIR TIKET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btn_Editar)
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Editar)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(13, 13, 13))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, -1, -1));
        jPanel1.add(Tipo_Servicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 280, 27));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josty25\\Documents\\NetBeansProjects\\EQUIPO7\\src\\com\\mycompany\\proyectofinal\\Imagenes\\FondoAzulXD.png")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Nombre_TexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_TexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_TexActionPerformed

    private void Numero_TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Numero_TelefonoActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        
        String nombre=Nombre_Tex.getText();
        String apellido=Numero_Telefono.getText(); 
        String tipoVehiculo=Marco_Cliente.getText();
        String horaLavado = Hora_Cliente.getText(); 
        String tip = Tipo_Servicios.getText();
        
        Solicitud solicitud = new Solicitud(nombre, apellido, tipoVehiculo, horaLavado, tip);
        
        Cliente cliente= new Cliente("192.168.1.110",1020);
        cliente.enviarSolicitud(solicitud);
        
        
        if(ticket == null){
            ticket = new Tiket();
        }
       
        AlmecenarCliente.append(solicitud.toString());
    
        ticket.guardarDatos(nombre, tip, horaLavado);
        
        Nombre_Tex.setText("");
        Numero_Telefono.setText(""); 
        Marco_Cliente.setText("");
        Hora_Cliente.setText("");
        Tipo_Servicios.setText("");
    }//GEN-LAST:event_GuardarActionPerformed

    private void btn_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegresarActionPerformed
        Principal i = new Principal();
        i.setVisible(true);
        dispose();        
    }//GEN-LAST:event_btn_RegresarActionPerformed

    private void btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarActionPerformed
        AlmecenarCliente.setEditable(true);
    }//GEN-LAST:event_btn_EditarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Tiket t = new Tiket();
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Hora_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hora_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hora_ClienteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AlmecenarCliente;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField Hora_Cliente;
    private javax.swing.JTextField Marco_Cliente;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField Nombre_Tex;
    private javax.swing.JTextField Numero_Telefono;
    private javax.swing.JTextField Tipo_Servicios;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_Regresar;
    private javax.swing.JLabel hora;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel ser;
    private javax.swing.JLabel telefono;
    private javax.swing.JLabel vehiculo;
    // End of variables declaration//GEN-END:variables
}
