/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabajofinallira;

/**
 *
 * @author emira
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        amlmacen = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_Agendar = new javax.swing.JButton();
        btn_Servicios = new javax.swing.JButton();
        btn_Promociones = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        btn_Promociones1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        amlmacen.setText("CHECAR DATOS");
        amlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amlmacenActionPerformed(evt);
            }
        });
        jPanel1.add(amlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 210, 50));

        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josty25\\Documents\\NetBeansProjects\\EQUIPO7\\src\\Imagenes\\Logo.png")); // NOI18N
        logo.setText("Logo");
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josty25\\Documents\\NetBeansProjects\\EQUIPO7\\src\\Imagenes\\titulo.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        btn_Agendar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josty25\\Documents\\NetBeansProjects\\EQUIPO7\\src\\Imagenes\\botonf.png")); // NOI18N
        btn_Agendar.setText("AGENDAR CLIENTES");
        btn_Agendar.setContentAreaFilled(false);
        btn_Agendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgendarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Agendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 280, 70));

        btn_Servicios.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josty25\\Documents\\NetBeansProjects\\EQUIPO7\\src\\Imagenes\\boton6.png")); // NOI18N
        btn_Servicios.setText("SERVICIOS");
        btn_Servicios.setContentAreaFilled(false);
        btn_Servicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ServiciosActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Servicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 270, 70));

        btn_Promociones.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josty25\\Documents\\NetBeansProjects\\EQUIPO7\\src\\Imagenes\\boton3.png")); // NOI18N
        btn_Promociones.setText("PROMOCIONES");
        btn_Promociones.setContentAreaFilled(false);
        btn_Promociones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PromocionesActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Promociones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 280, -1));

        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josty25\\Documents\\NetBeansProjects\\EQUIPO7\\src\\Imagenes\\fondo.jpg")); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btn_Promociones1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josty25\\Documents\\NetBeansProjects\\EQUIPO7\\src\\Imagenes\\boton3.png")); // NOI18N
        btn_Promociones1.setText("PROMOCIONES");
        btn_Promociones1.setContentAreaFilled(false);
        btn_Promociones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Promociones1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Promociones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 280, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgendarActionPerformed
        AgendarCita a = new AgendarCita();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_AgendarActionPerformed

    private void btn_ServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ServiciosActionPerformed
        Servicios s = new Servicios();
        s.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btn_ServiciosActionPerformed

    private void btn_PromocionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PromocionesActionPerformed
        Promociones p = new Promociones();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_PromocionesActionPerformed

    private void btn_Promociones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Promociones1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Promociones1ActionPerformed

    private void amlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amlmacenActionPerformed
        Almacen a = new Almacen();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_amlmacenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton amlmacen;
    private javax.swing.JButton btn_Agendar;
    private javax.swing.JButton btn_Promociones;
    private javax.swing.JButton btn_Promociones1;
    private javax.swing.JButton btn_Servicios;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
