/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabajofinallira;

import java.awt.BorderLayout;

/**
 *
 * @author Josty25
 */
public class Promociones extends javax.swing.JFrame {

    /**
     * Creates new form Promociones
     */
    public Promociones() {
        initComponents();
        
        
        PromocionJpanel1 pr1 = new PromocionJpanel1();
        pr1.setSize(850, 425);
        pr1.setLocation(0, 0);
        
        PanelPromociones.removeAll();
        PanelPromociones.add(pr1, BorderLayout.CENTER);
        PanelPromociones.revalidate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_regresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PanelPromociones = new javax.swing.JPanel();
        btn_promo1 = new javax.swing.JButton();
        btn_promo2 = new javax.swing.JButton();
        btn_promo3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_regresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_regresar.setText("<--");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 48, 68, 30));

        jLabel1.setFont(new java.awt.Font("Barlow Black", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PROMOCIONES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 22, -1, -1));

        PanelPromociones.setBackground(new java.awt.Color(0, 0, 0));
        PanelPromociones.setPreferredSize(new java.awt.Dimension(850, 435));

        javax.swing.GroupLayout PanelPromocionesLayout = new javax.swing.GroupLayout(PanelPromociones);
        PanelPromociones.setLayout(PanelPromocionesLayout);
        PanelPromocionesLayout.setHorizontalGroup(
            PanelPromocionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        PanelPromocionesLayout.setVerticalGroup(
            PanelPromocionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        jPanel1.add(PanelPromociones, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 143, -1, -1));

        btn_promo1.setText("1er Promociones");
        btn_promo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_promo1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_promo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 104, -1, -1));

        btn_promo2.setText("2da Promociones");
        btn_promo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_promo2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_promo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 104, -1, -1));

        btn_promo3.setText("3ra Promociones");
        btn_promo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_promo3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_promo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 104, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_promo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_promo1ActionPerformed
        PromocionJpanel1 pr1 = new PromocionJpanel1();
        pr1.setSize(850, 425);
        pr1.setLocation(0, 0);
        
        PanelPromociones.removeAll();
        PanelPromociones.add(pr1, BorderLayout.CENTER);
        PanelPromociones.revalidate();
    }//GEN-LAST:event_btn_promo1ActionPerformed

    private void btn_promo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_promo3ActionPerformed
        
    }//GEN-LAST:event_btn_promo3ActionPerformed

    private void btn_promo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_promo2ActionPerformed
        PromocionJpanel2 pr2 = new PromocionJpanel2();
        pr2.setSize(850, 425);
        pr2.setLocation(0, 0);
        
        PanelPromociones.removeAll();
        PanelPromociones.add(pr2, BorderLayout.CENTER);
        PanelPromociones.revalidate();
    }//GEN-LAST:event_btn_promo2ActionPerformed

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        InicioCarwash i = new InicioCarwash();
        i.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Promociones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Promociones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Promociones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Promociones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Promociones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPromociones;
    private javax.swing.JButton btn_promo1;
    private javax.swing.JButton btn_promo2;
    private javax.swing.JButton btn_promo3;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
