/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabajofinallira;

import com.mycompany.proyectofinal.Imagenes.PanelesAparte.ServicioBasicoYVip;
import com.mycompany.proyectofinal.Imagenes.PanelesAparte.ServicioSelecto;
import java.awt.BorderLayout;

/**
 *
 * @author Josty25
 */
public class Servicios extends javax.swing.JFrame{

    /**
     * Creates new form Servicios
     */
    public Servicios() {
        initComponents();
        setLocationRelativeTo(null);
        
        com.mycompany.proyectofinal.Imagenes.PanelesAparte.ServicioBasicoYVip s = new ServicioBasicoYVip();
        s.setSize(850, 500);
        s.setLocation(0, 0);
        
        PanellMostrar.removeAll();
        PanellMostrar.add(s, BorderLayout.CENTER);
        PanellMostrar.revalidate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        Regresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PanellMostrar = new javax.swing.JPanel();
        mostrarServicio1 = new javax.swing.JButton();
        MostrarServicios2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        PanelPrincipal.setPreferredSize(new java.awt.Dimension(1000, 600));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Regresar.setText("<----");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        PanelPrincipal.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 34, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Impact", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("SERVICIOS");
        PanelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 6, 229, 76));

        PanellMostrar.setOpaque(false);
        PanellMostrar.setPreferredSize(new java.awt.Dimension(850, 500));

        javax.swing.GroupLayout PanellMostrarLayout = new javax.swing.GroupLayout(PanellMostrar);
        PanellMostrar.setLayout(PanellMostrarLayout);
        PanellMostrarLayout.setHorizontalGroup(
            PanellMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        PanellMostrarLayout.setVerticalGroup(
            PanellMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        PanelPrincipal.add(PanellMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 80, -1, -1));

        mostrarServicio1.setText("1er Servicio");
        mostrarServicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarServicio1ActionPerformed(evt);
            }
        });
        PanelPrincipal.add(mostrarServicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 34, -1, -1));

        MostrarServicios2.setText("2do Servicio");
        MostrarServicios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarServicios2ActionPerformed(evt);
            }
        });
        PanelPrincipal.add(MostrarServicios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(769, 35, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josty25\\Documents\\NetBeansProjects\\EQUIPO7\\src\\com\\mycompany\\proyectofinal\\Imagenes\\FondosPs3.jpg")); // NOI18N
        PanelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        Principal car = new Principal();
        car.setVisible(true);
        dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void mostrarServicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarServicio1ActionPerformed
        com.mycompany.proyectofinal.Imagenes.PanelesAparte.ServicioBasicoYVip s = new ServicioBasicoYVip();
        s.setSize(850, 500);
        s.setLocation(0, 0);
        
        
        
        PanellMostrar.removeAll();
        PanellMostrar.add(s, BorderLayout.CENTER);
        PanellMostrar.revalidate();
    }//GEN-LAST:event_mostrarServicio1ActionPerformed

    private void MostrarServicios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarServicios2ActionPerformed
        com.mycompany.proyectofinal.Imagenes.PanelesAparte.ServicioSelecto ser = new ServicioSelecto();
        ser.setSize(850, 500);
        ser.setLocation(0, 0);
        
        PanellMostrar.removeAll();
        PanellMostrar.add(ser, BorderLayout.CENTER);
        PanellMostrar.revalidate();
    }//GEN-LAST:event_MostrarServicios2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MostrarServicios2;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PanellMostrar;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton mostrarServicio1;
    // End of variables declaration//GEN-END:variables

}
