/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabajofinallira;

import com.mycompany.proyectofinal.Imagenes.PanelesAparte.ServicioBasicoYVip;
import com.mycompany.proyectofinal.Imagenes.PanelesAparte.ServicioSelecto;
import java.awt.BorderLayout;

/**
 *
 * @author Josty25
 */
public class Servicios extends javax.swing.JFrame{

    /**
     * Creates new form Servicios
     */
    public Servicios() {
        initComponents();
        setLocationRelativeTo(null);
        
        com.mycompany.proyectofinal.Imagenes.PanelesAparte.ServicioBasicoYVip s = new ServicioBasicoYVip();
        s.setSize(850, 500);
        s.setLocation(0, 0);
        
        PanellMostrar.removeAll();
        PanellMostrar.add(s, BorderLayout.CENTER);
        PanellMostrar.revalidate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        Regresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PanellMostrar = new javax.swing.JPanel();
        mostrarServicio1 = new javax.swing.JButton();
        MostrarServicios2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        PanelPrincipal.setPreferredSize(new java.awt.Dimension(1000, 600));

        Regresar.setText("<----");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Impact", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SERVICIOS");

        PanellMostrar.setPreferredSize(new java.awt.Dimension(850, 500));

        javax.swing.GroupLayout PanellMostrarLayout = new javax.swing.GroupLayout(PanellMostrar);
        PanellMostrar.setLayout(PanellMostrarLayout);
        PanellMostrarLayout.setHorizontalGroup(
            PanellMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        PanellMostrarLayout.setVerticalGroup(
            PanellMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        mostrarServicio1.setText("1er Servicio");
        mostrarServicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarServicio1ActionPerformed(evt);
            }
        });

        MostrarServicios2.setText("2do Servicio");
        MostrarServicios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarServicios2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(PanellMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Regresar)
                        .addGap(130, 130, 130)
                        .addComponent(mostrarServicio1)
                        .addGap(103, 103, 103)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(MostrarServicios2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Regresar)
                            .addComponent(mostrarServicio1))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MostrarServicios2)
                        .addGap(18, 18, 18)))
                .addComponent(PanellMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        InicioCarwash car = new InicioCarwash();
        car.setVisible(true);
        dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void mostrarServicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarServicio1ActionPerformed
        com.mycompany.proyectofinal.Imagenes.PanelesAparte.ServicioBasicoYVip s = new ServicioBasicoYVip();
        s.setSize(850, 500);
        s.setLocation(0, 0);
        
        
        
        PanellMostrar.removeAll();
        PanellMostrar.add(s, BorderLayout.CENTER);
        PanellMostrar.revalidate();
    }//GEN-LAST:event_mostrarServicio1ActionPerformed

    private void MostrarServicios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarServicios2ActionPerformed
        com.mycompany.proyectofinal.Imagenes.PanelesAparte.ServicioSelecto ser = new ServicioSelecto();
        ser.setSize(850, 500);
        ser.setLocation(0, 0);
        
        PanellMostrar.removeAll();
        PanellMostrar.add(ser, BorderLayout.CENTER);
        PanellMostrar.revalidate();
    }//GEN-LAST:event_MostrarServicios2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MostrarServicios2;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PanellMostrar;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton mostrarServicio1;
    // End of variables declaration//GEN-END:variables

}
